apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hygiene-testsite
  annotations:
    siliconsaga.org/aspects: website-hygiene
    siliconsaga.org/aspect-versions: website-hygiene@1.0
spec:
  type: website
  lifecycle: production
  owner: group:default/team-devex
